# ABOUTME: Docker Compose configuration using SQLite instead of PostgreSQL
# ABOUTME: Lighter alternative for development without database container

version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    environment:
      FLASK_APP: app
      FLASK_ENV: development
      # Don't set DATABASE_URL - let config.py use absolute path
      SECRET_KEY: dev-secret-key-change-in-production
      LDAP_HOST: ${LDAP_HOST:-ldap://your-ad-server}
      LDAP_PORT: ${LDAP_PORT:-389}
      LDAP_BASE_DN: ${LDAP_BASE_DN:-dc=example,dc=com}
      LDAP_BIND_USER_DN: ${LDAP_BIND_USER_DN}
      LDAP_BIND_USER_PASSWORD: ${LDAP_BIND_USER_PASSWORD}
      MEDIAMTX_WEBHOOK_SECRET: ${MEDIAMTX_WEBHOOK_SECRET:-shared-secret}
      SESSION_COOKIE_SECURE: "False"
    volumes:
      - .:/app
      - /app/__pycache__
      - sqlite_data:/app/instance
    ports:
      - "5000:5000"
    command: sh -c "python init_sqlite.py --skip-prompt && python app.py"

  # Optional: MediaMTX server for testing
  mediamtx:
    image: bluenviron/mediamtx:latest
    ports:
      - "8554:8554"  # RTSP
      - "1935:1935"  # RTMP
      - "8888:8888"  # HLS
      - "8889:8889"  # WebRTC
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
    environment:
      - MTX_PROTOCOLS=tcp
    profiles:
      - with-mediamtx

volumes:
  sqlite_data:
